from graphene import ObjectType
from graphene import Int, String


class Company(ObjectType):
    name = String()
    catchPhrase = String()
    bs = String()

class Geo(ObjectType):
    lat = String()
    lng = String()

class Address(ObjectType):
    street = String()
    suite = String()
    city = String()
    zipcode = String()
    geo = Geo()

class User(ObjectType):
    id = Int()
    name = String()
    username = String()
    email = String()
    phone = String()
    website = String()
    company = Company()
    address = Address()



# type Company {
#   name: String
#   catchPhrase: String
#   bs: String
# }

# type Geo {
#   lat: String
#   lng: String
# }

# type Address {
#   street: String
#   suite: String
#   city: String
#   zipcode: String
#   geo: Geo
# }

# type AutogeneratedMainType {
#   id: Int
#   name: String
#   username: String
#   email: String
#   phone: String
#   website: String
#   company: Company
#   address: Address
# }
